### ISSUE TITLE
use custom_message on phoneVerificationStart

### ISSUE THREAD

**Issue by nickfun** [twilio/authy-php#31]
The phoneVerificationStart method does not allow a parameter for setting a custom message. Please add this feature as it is supported in the public API.

**Comment by rubaiet** [comment]
They might forgot this app!

**Comment by serargz** [comment]
@nickfun thanks for reporting. We are catching up with issues and pull requests, will get back to you on this.

**Comment by jonaslejon** [comment]
Any news about this feature?

**Comment by luisuribe** [comment]
This is included in the new version that will be released soon (about two weeks)
