### ISSUE TITLE
Update phpunit to 6+

### ISSUE THREAD

**Issue by robinske** [twilio/authy-php#46]
Our tests have syntax that [breaks in version 6+](https://stackoverflow.com/questions/6065730/why-fatal-error-class-phpunit-framework-testcase-not-found-in/42561590#42561590) and version 5 is [unsupported as of this month](https://phpunit.de/).

Our [Travis build seems to expect version 5.x](https://travis-ci.org/authy/authy-php/builds/347534257), but there's nothing that enforces that when you run it locally. If there's a way to specify the phpunit version, let's do that!

**Comment by aaronhuisinga** [comment]
I took care of this in #80 along with updating other dependencies.
