### ISSUE TITLE
Unable to Change Locale. (SMS Language)

### ISSUE THREAD

**Issue by deepak1725** [twilio/authy-php#56]
1. On Twilio, Default locale is Identified on basis of Country code, But on Authy its documented as "en" (English)

2. There is no way to overide default locale. For Ex, I want to set language as "English" default was "Hindi", as per Twilio, i need to pass `locale = 'en' ` in request params , but in 
`Authy->phoneVerificationStart` there is no way to pass that param, i need to manually edit this function to add this param, to got it working.

Please add Twilio supported Params,
https://www.twilio.com/docs/verify/api/verification#request-a-verification-code

**Comment by nmargaritis** [comment]
Had the same issue, I've seen that the master has been updated to reflect this change. Please proceed with the release.

**Comment by luisuribe** [comment]
Yes. It's already released.
