### ISSUE TITLE
Conflict in dependancies with spring boot 2.0.5

### ISSUE THREAD

**Issue by rclarke1** [twilio/authy-php#60]
For anyone using spring boot 2.0.5, I was getting the following error during runtime
`java.lang.NoSuchMethodError: org.json.JSONObject`

to resolve I needed to exclude the following com.vaadin.external.google from  spring-boot-starter-test:
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		   	<exclusions>
		   		<exclusion> 
		          	<groupId>com.vaadin.external.google</groupId>
		          	<artifactId>android-json</artifactId>
		       </exclusion>
     			</exclusions> 
		</dependency>
```
As that package had its own org.json dependency. Hope this saves someone some time

**Comment by luisuribe** [comment]
This doesn't look as an issue for this library.
