### ISSUE TITLE
Upgrade to Guzzle 7.x

### ISSUE THREAD

**Issue by idoqo** [twilio/authy-php#79]
Laravel 8 just got released and ships with Guzzle version 7.x out of the box. For now, the package can't be used in a new Laravel 8 project as the current stable release (3.0.5) requires Guzzle v6.0.x and the RC (3.1.0) requires v6.5.x.
Installing it produces the error below:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].
    - authy/php 3.0.4 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - authy/php 3.0.5 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - authy/php 3.1.0-rc1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - authy/php v3.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for authy/php ^3.0 -> satisfiable by authy/php[3.0.4, 3.0.5, 3.1.0-rc1, v3.0]
```

**Comment by dzung1nguyen** [comment]
Laravel 8.x same error. can you update date the composer.json (guzzlehttp/guzzle  from v7). Thank you.

**Comment by aaronhuisinga** [comment]
PR for this is open at #80

**Comment by erikvanderschaaf** [comment]
Any news on a stable release for this?

**Comment by trylika** [comment]
any updates on stable release?

**Comment by mtt786** [comment]
It works for me in Laravel 9.x
`composer require authy/php:^2.1`

**Comment by robinske** [comment]
This library is no longer actively maintained. The Authy API has been replaced with the [Twilio Verify API](https://www.twilio.com/docs/verify). Twilio will support the Authy API through November 1, 2022 for SMS/Voice. After this date, we’ll start to deprecate the service for SMS/Voice. Any requests sent to the API after May 1, 2023, will automatically receive an error.  Push and TOTP will continue to be supported through July 2023.

[Learn more about migrating from Authy to Verify.](https://www.twilio.com/blog/migrate-authy-to-verify)

Please visit the Twilio Docs for:
* [Verify + PHP (Laravel) quickstart](https://www.twilio.com/docs/verify/quickstarts/php-laravel)
* [Twilio PHP helper library](https://www.twilio.com/docs/libraries/php)
* [Verify API reference](https://www.twilio.com/docs/verify/api)

Please direct any questions to [Twilio Support](https://support.twilio.com/hc/en-us). Thank you!
