### ISSUE TITLE
QR Code method missing from 4.x release

### ISSUE THREAD

**Issue by aaronhuisinga** [twilio/authy-php#82]
Somehow the qrCode method was merged directly into a 3.x release branch, and is missing from the 4.x release due to it not being available in master.

The PR in question: https://github.com/twilio/authy-php/pull/61

**Comment by aaronhuisinga** [comment]
Opened https://github.com/twilio/authy-php/pull/83 to fix this. @luisuribe can we get this merged ASAP? This is an unintended breaking change in v4.x.

**Comment by luisuribe** [comment]
Done! Thanks for the PR

**Comment by aaronhuisinga** [comment]
Thanks for the prompt merge @luisuribe! Can we get an updated release tagged as well?
